// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	OPENAI_API_KEY: string;
	FIREWORKS_API_KEY: string;
	GROQ_API_KEY: string;
	ANTHROPIC_API_KEY: string;
	[x: string]: string | undefined;
}
